package com.cshep4.premierpredictor.auth.exception

class InternalException(cause: Throwable?) : Exception(cause)
